### ISSUE TITLE
error on vnc no auth server

### ISSUE THREAD

**Issue by emdaitaj** [pschmitt/conntest#1]
hi
thank you for this great tool
i've been looking for some thing like this for long time

wanted to report and bug
when you try to connect to vnc server which doesn't require any password 
the library freezes and you must send "ctl+C" key to ccancel . and the problem is after canceling one time you can't the the lib any more

` 
aceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "conntest/conntest.py", line 163, in vnc_connection
    reactor.run()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1198, in run
    self.startRunning(installSignalHandlers=installSignalHandlers)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1178, in startRunning
    ReactorBase.startRunning(self)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 687, in startRunning
    raise error.ReactorNotRestartable()
twisted.internet.error.ReactorNotRestartable
`
(this is generated after canceling one time (must reload the python to fix) and without canceling it works well)
(i f you don't have any no password vnc server skype me to receive skype:muhammad.emaditaj)

thanks alot for this

**Comment by pschmitt** [comment]
You are welcome. I could verify the issue you were having.
The thing is that I have literally no experience with twisted, no idea why the runner does not exit properly...

**Comment by emdaitaj** [comment]
can you just fix it so it'll support servers with no authentication

**Comment by pschmitt** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10212754-332715170_1-s4-v1.png?transparent=1&palette=1&width=246)

@emdaitaj I just told that I have no idea how to "just fix it".
